--First connection

--Before all
UPDATE Projects
SET Name='Original Project'
Where Id = 12

SELECT TOP 10 * FROM [Projects] WHERE [Id] = 12
GO

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

BEGIN TRANSACTION T1
	UPDATE Projects
	SET Name='Updated in T1'
	Where Id = 12
COMMIT TRANSACTION T1;
ROLLBACK TRANSACTION T1;
GO


--SET TRANSACTION ISOLATION LEVEL Read committed
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRANSACTION T1
	UPDATE Projects
	SET Name='Updated in T1'
	Where Id = 12
COMMIT TRANSACTION T1;
ROLLBACK TRANSACTION T1;
GO


-- Second connection

--SET TRANSACTION ISOLATION LEVEL Read committed
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION T1
SELECT TOP 10 * FROM [Projects] WHERE [Id] = 12
ROLLBACK TRANSACTION T1
GO

--SET TRANSACTION ISOLATION LEVEL Read committed
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION T1
SELECT TOP 100 * FROM [Projects] WHERE [Id] = 12
ROLLBACK TRANSACTION T1
GO