version: '3'

services:
  mongo-database:
    image: mongo:latest
    container_name: mongo-database
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword123
      MONGO_INITDB_DATABASE: TestDb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword123
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword123@mongo-database:27017